backend/src/api/urls.py
from django.urls import include, path
from django.contrib import admin


urlpatterns = [
    path("api/forms/", include("forms.urls")),
    path("api/insurance/", include("insurance.urls")),
    path("api/discussion/", include("discussion.urls")),
    path("admin/", admin.site.urls),
]

backend/src/insurance/urls.py
from django.urls import path, include
from .views import CaseViewSet
from rest_framework import routers

router = routers.DefaultRouter(trailing_slash=False)
router.register(r"case", CaseViewSet)

urlpatterns = [
    path("", include(router.urls)),
]

backend/src/insurance/models.py
from datetime import timedelta
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone
from forms.models import ScheduledMessage


class ContactMethod(models.TextChoices):
    EMAIL = "EMAIL", "Email"
    WHATSAPP = "WHATSAPP", "WhatsApp"
    PHONE = "PHONE", "Phone"


class Occupation(models.TextChoices):
    EMPLOYEE = "employee", "Employee"
    AZUBI = "azubi", "Azubi"
    STUDENT_EMPLOYEE = "studentEmployee", "Student (working)"
    STUDENT_SELFEMPLOYED = "studentSelfEmployed", "Student (self-employed)"
    STUDENT_UNEMPLOYED = "studentUnemployed", "Student (unemployed)"
    SELF_EMPLOYED = "selfEmployed", "Self-employed"
    UNEMPLOYED = "unemployed", "Unemployed"
    OTHER = "other", "Other/unknown"


class Intent(models.TextChoices):
    GENERAL = "general", "General question"
    PRIVATE = "private", "Choose private health insurance"
    PUBLIC = "public", "Choose public health insurance"
    EXPAT = "expat", "Choose expat health insurance"


class Brokers(models.TextChoices):
    CHRISTINA_WEBER = "christina-weber", "Christina Weber"
    SEAMUS_WOLF = "seamus-wolf", "Seamus Wolf"


class Case(models.Model):
    """
    A need that usually results in an insurance policy being signed.
    """

    name = models.CharField(max_length=100)
    email = models.EmailField(blank=True)
    contact_method = models.CharField(
        "Contact method", max_length=15, choices=ContactMethod, default=ContactMethod.EMAIL
    )

    occupation = models.CharField(max_length=50, choices=Occupation, default=Occupation.OTHER)
    income = models.PositiveIntegerField("Yearly income", blank=True, null=True, default=None)
    age = models.PositiveSmallIntegerField(blank=True, null=True, default=None)
    is_married = models.BooleanField(null=True, default=None)
    children_count = models.PositiveSmallIntegerField(blank=True, null=True, default=None)
    is_applying_for_first_visa = models.BooleanField(default=None, null=True)
    has_german_public_insurance = models.BooleanField(default=None, null=True)
    has_eu_public_insurance = models.BooleanField(default=None, null=True)

    intent = models.CharField(max_length=50, choices=Intent, default=Intent.GENERAL)

    creation_date = models.DateTimeField(auto_now_add=True)
    question = models.TextField("Question", blank=True)

    broker = models.CharField(max_length=30, choices=Brokers, default=Brokers.SEAMUS_WOLF)
    referrer = models.CharField(blank=True, help_text="Part of the commissions will be paid out to that referrer")

    daily_digest_fields = [
        "intent",
        "broker",
        "contact_method",
        "income",
        "occupation",
        "name",
        "age",
        "is_married",
        "children_count",
        "question",
    ]

    def clean(self):
        super().clean()
        if self.contact_method == ContactMethod.EMAIL and not self.email:
            raise ValidationError({"email": "Email is required when contact_method is EMAIL."})

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.email:
            CustomerNotification.objects.get_or_create(case=self)
            FeedbackNotification.objects.get_or_create(case=self)

        if self.contact_method != ContactMethod.WHATSAPP:
            BrokerNotification.objects.get_or_create(case=self)

    @property
    def broker_info(self):
        return {
            "christina-weber": {
                "is_male": False,
                "first_name": "Christina",
                "full_name": "Christina Weber",
                "email": "hello@feather-insurance.com",
            },
            "seamus-wolf": {
                "is_male": True,
                "first_name": "Seamus",
                "full_name": "Seamus Wolf",
                "email": "Seamus.Wolf@horizon65.com",
            },
        }[self.broker]

    class Meta:
        verbose_name = "Insurance case"
        ordering = ["-creation_date"]

    def __str__(self):
        return self.name


def in_1_week():
    return timezone.now() + timedelta(weeks=1)


class CaseNotificationMixin(ScheduledMessage):
    case = models.ForeignKey(Case, on_delete=models.CASCADE)

    class Meta:
        abstract = True


class CustomerNotification(CaseNotificationMixin, ScheduledMessage):
    template = "customer-notification.html"

    @property
    def recipients(self) -> list[str]:
        return [
            self.case.email,
        ]

    @property
    def subject(self) -> str:
        return f"{self.case.broker_info['first_name']} will contact you soon"

    class Meta(ScheduledMessage.Meta):
        pass


class BrokerNotification(CaseNotificationMixin, ScheduledMessage):
    template = "broker-notification.html"

    @property
    def recipients(self) -> list[str]:
        return [
            self.case.broker_info["email"],
        ]

    @property
    def subject(self) -> str:
        return f"Insurance question from {self.case.name} (All About Berlin)"

    @property
    def reply_to(self) -> str:
        return self.case.email

    class Meta(ScheduledMessage.Meta):
        pass


class FeedbackNotification(CaseNotificationMixin):
    template = "feedback-notification.html"
    delivery_date = models.DateTimeField(default=in_1_week)

    @property
    def subject(self) -> str:
        return f"Did {self.case.broker_info['first_name']} help you get insured?"

    @property
    def recipients(self) -> list[str]:
        return [
            self.case.email,
        ]

    class Meta(ScheduledMessage.Meta):
        pass

backend/src/insurance/views.py
from .models import Case
from .serializers import CaseSerializer
from forms.views import MessageViewSet


class CaseViewSet(MessageViewSet):
    queryset = Case.objects.all()
    serializer_class = CaseSerializer

backend/src/insurance/templates/broker-notification.html
<p>Hi {{ message.case.broker_info.name|default:"there" }},</p>

<p>Someone asked you a question on All About Berlin.</p>

<p><strong>Name:</strong> {{ message.case.name|default:"Not specified" }}</p>
<p><strong>Email:</strong> {{ message.case.email|default:"Not specified" }}</p>
<p><strong>Referrer:</strong> {{ message.case.referrer|default:"Not specified" }}</p>
<hr>
<p><strong>Occupation:</strong> {{ message.case.get_occupation_display }}</p>
<p><strong>Income:</strong> {{ message.case.income|default_if_none:"Not specified" }}</p>
<p><strong>Age:</strong> {{ message.case.age|default_if_none:"Not specified" }}</p>
<p><strong>Married:</strong> {{ message.case.is_married|yesno:"Yes,No,Not specified" }}</p>
<p><strong>Number of children:</strong> {{ message.case.children_count|default_if_none:"Not specified" }}</p>
<p><strong>Has public health insurance in Germany:</strong> {{ message.case.has_german_public_insurance|yesno:"Yes,No,Not specified" }}</p>
<p><strong>Has public health insurance in the EU:</strong> {{ message.case.has_eu_public_insurance|yesno:"Yes,No,Not specified" }}</p>
<p><strong>Applying for a first visa/residence permit:</strong> {{ message.case.is_applying_for_first_visa|yesno:"Yes,No,Not specified" }}</p>
<hr>
<p><strong>Intent: {{ message.case.get_intent_display }}</strong></p>
<p><strong>Question:</strong><br>{{ message.case.question|default:"Not specified"|linebreaksbr }}</p>

backend/src/insurance/templates/customer-notification.html
<p>Hi {{ message.case.name|default:"there" }},</p>

<p>You asked a health insurance question on All About Berlin. {{ message.case.broker_info.first_name }} will reply today or tomorrow. I work with {{ message.case.broker_info.first_name }} because I trust {{ message.case.broker_info.is_male|yesno:"him,her"}}.</p>

<p>While you wait, you can also...</p>

<ul>
	<li>Learn <a href="https://allaboutberlin.com/guides/german-health-insurance?utm_source=email_reminder">how German health insurance works</a></li>
	{% if message.case.occupation == 'selfEmployed' %}
		<li>Learn <a href="https://allaboutberlin.com/guides/freelance-visa?utm_source=email_reminder">how to apply for a freelance visa</a> or <a href="https://allaboutberlin.com/guides/renew-german-freelance-visa?utm_source=email_reminder">renew your freelance visa</a>.</li>
	{% elif message.case.occupation == 'employee' %}
		<li>Learn how to apply for a <a href="https://allaboutberlin.com/guides/work-visa?utm_source=email_reminder">work visa</a> or a <a href="https://allaboutberlin.com/guides/blue-card?utm_source=email_reminder">Blue Card</a>.</li>
	{% endif %}
	<li>Get <a href="https://allaboutberlin.com/guides/haftpflichtversicherung?utm_source=email_reminder">liability insurance</a>, because everyone should have it.</li>
</ul>

<p>Kind regards,<br>Nicolas Bouliane, All About Berlin</p>

<p><small>You received this email because you used the contact form on All About Berlin.</small></p>

backend/src/insurance/templates/feedback-notification.html
<p>Hi {{ message.case.name|default:"there" }},</p>

<p>A week ago, you asked a health insurance question on All About Berlin.</p>

<p>If you have time, I would like some feedback:</p>

<ol>
	<li>Did my health insurance tool help?</li>
	<li>Did your conversation with {{ message.case.broker_info.first_name }} help?</li>
	<li>What can I explain better in my health insurance guide?</li>
</ol>

<p>Thanks for taking the time to answer. It's really helpful.</p>

<p>Kind regards,<br>Nicolas Bouliane, All About Berlin</p>

<p><small>You received this email because you asked a health insurance question on All About Berlin.</small></p>